name: Branch to be released

on:
  push:
    branches:
      # - 0.*.*
      - github_action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Build and push to Docker Hub 
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: melvinkcx/rds_pgpool
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Update README on Docker Hub
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_REPOSITORY: melvinkcx/rds_pgpool
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}